CREATE TABLE IF NOT EXISTS `SEARCH_CONFIG_OBJECT_BINDING` (
  `BIND_ID`          BIGINT NOT NULL,
  `SEARCH_CONFIG_ID` BIGINT NOT NULL,
  `OBJECT_ID`        BIGINT NOT NULL,
  `OBJECT_TYPE`      ENUM('entity') NOT NULL,
  `CREATED_BY`       BIGINT NOT NULL,
  `CREATED_ON`       TIMESTAMP(3) NOT NULL,
  PRIMARY KEY (`BIND_ID`),
  UNIQUE (`OBJECT_ID`, `OBJECT_TYPE`),
  CONSTRAINT `SC_BIND_CREATED_BY_FK` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER_GROUP` (`ID`) ON DELETE RESTRICT
);
