CREATE TABLE IF NOT EXISTS `DISCUSSION_THREAD_SUBMISSION_REFERENCE` (
  `THREAD_ID` BIGINT NOT NULL,
  `SUBMISSION_ID` BIGINT NOT NULL,
  PRIMARY KEY (`THREAD_ID`),
  UNIQUE (`SUBMISSION_ID`),
  INDEX `DISC_THREAD_SUB_REF_SUB_ID_IDX` (`SUBMISSION_ID`),
  CONSTRAINT `DISC_THREAD_SUB_REF_THREAD_FK` FOREIGN KEY (`THREAD_ID`) REFERENCES `DISCUSSION_THREAD` (`ID`) ON DELETE CASCADE
)
